language: node_js
services:
  - redis
node_js:
  - "12"
cache:
  directories:
  - "node_modules"
env:
  global:
    - CC_TEST_REPORTER_ID=733a59862b25edf5f27ab1fbc867c8ad0cd671c326cbda331f19f2d163c753a4
    - NODE_ENV=test
    - PORT=9000
    - LOGGER_TYPE=console
    - LOGGER_LEVEL=warn
    - HOST_IP=127.0.0.1
    - DEBUG=redis-cache-plugin
    - NODE_PATH=app/src
    - JWT_SECRET=mysecret
    - COOKIE_DOMAIN=mymachine
    - SESSION_KEY=test
    - PUBLIC_URL=http://localhost:9000
    - API_VERSION=v1
    - ALLOW_CONFIG_MUTATIONS=true
    - REDIS_URL=redis://localhost:6379
    - LOCAL_URL=http://127.0.0.1:3001
    - GATEWAY_URL=http://127.0.0.1:9000
    - MICROSERVICE_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
    - FASTLY_ENABLED=false
    - OKTA_API_KEY=example
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - yarn lint
  - yarn test
  - yarn run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
