version: "3"
services:
  develop:
    build: .
    ports:
      - "30505:30505"
    container_name: authorization
    env_file:
      - dev.env
    command: develop
    depends_on:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    image: redis
    container_name: authorization-redis
    ports:
      - "16379:6379"
    restart: always
