version: "3"
services:
  test:
    build: .
    ports:
      - "9000:9000"
    container_name: authorization-test
    environment:
      NODE_ENV: test
      SESSION_KEY: test
      PORT: 9000
      NODE_PATH: app/src
      JWT_SECRET: mysecret
      COOKIE_DOMAIN: mymachine
      PUBLIC_URL: http://127.0.0.1:9000
      SPARKPOST_KEY: fakeSparkpostKey
      REDIS_URL: redis
      ALLOW_CONFIG_MUTATIONS: "true"
      CT_URL: http://mymachine:8000
      CT_TOKEN: cttoken
      CT_REGISTER_MODE: autoa
      LOCAL_URL: http://127.0.0.1:9000
      HOST_IP: 127.0.0.1
      FASTLY_ENABLED: "false"
      GFW_APPLE_AUTH_KEY: "test"
    command: test
    depends_on:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: redis
    container_name: authorization-redis
    ports:
      - "16379:6379"
    restart: always
