version: "3"
services:
  test:
    build: .
    ports:
      - "9000:9000"
    container_name: authorization-test
    environment:
      NODE_ENV: test
      SESSION_KEY: test
      PORT: 9000
      NODE_PATH: app/src
      JWT_SECRET: mysecret
      COOKIE_DOMAIN: mymachine
      PUBLIC_URL: http://127.0.0.1:9000
      REDIS_URL: redis://redis:6379
      ALLOW_CONFIG_MUTATIONS: "true"
      GATEWAY_URL: http://mymachine:8000
      MICROSERVICE_TOKEN: cttoken
      LOCAL_URL: http://127.0.0.1:9000
      HOST_IP: 127.0.0.1
      FASTLY_ENABLED: "false"
      GFW_APPLE_AUTH_KEY: "test"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
      MONGO_HOST: mongo
      REQUIRE_API_KEY: true
    command: test
    depends_on:
      - redis
      - mongo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: redis
    container_name: authorization-redis
    ports:
      - "16379:6379"

  mongo:
    image: mongo:3.6
    ports:
      - "27017"
