version: "3"
services:
  test:
    build: .
    ports:
      - "9000:9000"
    container_name: authorization-test
    environment:
      NODE_ENV: test
      SESSION_KEY: test
      PORT: 9000
      LOGGER_TYPE: console
      DEBUG: redis-cache-plugin
      NODE_PATH: app/src
      JWT_SECRET: mysecret
      COOKIE_DOMAIN: mymachine
      PUBLIC_URL: http://localhost:9000
      SPARKPOST_KEY: fakeSparkpostKey
      MONGO_PORT_27017_TCP_ADDR: mongo
      REDIS_URL: redis
      ALLOW_CONFIG_MUTATIONS: "true"
    command: test
    depends_on:
      - mongo
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongo:
    image: mongo:3.6.13
    command: --smallfiles
    ports:
      - "27017"

  redis:
    image: redis
    container_name: authorization-redis
    ports:
      - "16379:6379"
    restart: always
