version: "3"
services:
  debug:
    build: .
    ports:
      - "9000:9000"
      - "9229:9229"
    container_name: authorization
    env_file:
      - dev.env
    command: debug
    depends_on:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    image: redis
    container_name: authorization-redis
    ports:
      - "6379:6379"
    restart: always
  mongo:
    image: mongo:3.6
    conatiner_name: authorization-mongo
    ports:
      - "27017"