apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: authorization
  name: authorization
  namespace: gateway
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      name: authorization
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: authorization
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - gateway
      containers:
      - args:
        - start
        env:
        - name: PORT
          value: "9000"
        - name: LOGGER_TYPE
          value: console
        - name: LOGGER_LEVEL
          value: debug
        - name: DEBUG
          value: oauth-plugin
        - name: NODE_ENV
          value: prod
        - name: NODE_PATH
          value: app/src
        - name: BASICAUTH_USERNAME
          value: vizzuality
        - name: CONFIRM_URL_REDIRECT
          value: http://www.globalforestwatch.org
        - name: PUBLIC_URL
          value: http://production-api.globalforestwatch.org
        - name: APP_NAME
          value: RW API
        - name: APP_LOGO
          value: http://www.wri.org/sites/all/themes/wri/images/logo.png
        - name: APP_COLOR
          value: '#f1b319'
        - name: CT_MONGO_URI
          valueFrom:
            secretKeyRef:
              key: CT_MONGO_URI
              name: authorization
        - name: SESSION_KEY
          valueFrom:
            secretKeyRef:
              key: SESSION_KEY
              name: authorization
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: JWT_SECRET
              name: authorization
        - name: GFW_TWITTER_CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              key: GFW_TWITTER_CONSUMER_KEY
              name: authorization
        - name: GFW_TWITTER_CONSUMER_SECRET
          valueFrom:
            secretKeyRef:
              key: GFW_TWITTER_CONSUMER_SECRET
              name: authorization
        - name: GFW_FACEBOOK_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: GFW_FACEBOOK_CLIENT_ID
              name: authorization
        - name: GFW_FACEBOOK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: GFW_FACEBOOK_CLIENT_SECRET
              name: authorization
        - name: GFW_GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: GFW_GOOGLE_CLIENT_ID
              name: authorization
        - name: GFW_GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: GFW_GOOGLE_CLIENT_SECRET
              name: authorization
        - name: RW_TWITTER_CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              key: RW_TWITTER_CONSUMER_KEY
              name: authorization
        - name: RW_TWITTER_CONSUMER_SECRET
          valueFrom:
            secretKeyRef:
              key: RW_TWITTER_CONSUMER_SECRET
              name: authorization
        - name: RW_FACEBOOK_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: RW_FACEBOOK_CLIENT_ID
              name: authorization
        - name: RW_FACEBOOK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: RW_FACEBOOK_CLIENT_SECRET
              name: authorization
        - name: RW_GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: RW_GOOGLE_CLIENT_ID
              name: authorization
        - name: RW_GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: RW_GOOGLE_CLIENT_SECRET
              name: authorization
        - name: PREP_TWITTER_CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              key: PREP_TWITTER_CONSUMER_KEY
              name: authorization
        - name: PREP_TWITTER_CONSUMER_SECRET
          valueFrom:
            secretKeyRef:
              key: PREP_TWITTER_CONSUMER_SECRET
              name: authorization
        - name: PREP_FACEBOOK_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: PREP_FACEBOOK_CLIENT_ID
              name: authorization
        - name: PREP_FACEBOOK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: PREP_FACEBOOK_CLIENT_SECRET
              name: authorization
        - name: PREP_GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: PREP_GOOGLE_CLIENT_ID
              name: authorization
        - name: PREP_GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: PREP_GOOGLE_CLIENT_SECRET
              name: authorization
        - name: BASICAUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              key: BASICAUTH_PASSWORD
              name: authorization
        - name: SPARKPOST_KEY
          valueFrom:
            secretKeyRef:
              key: SPARKPOST_KEY
              name: authorization
        - name: INSTAPUSH_TOKEN
          valueFrom:
            secretKeyRef:
              key: INSTAPUSH_TOKEN
              name: authorization
        - name: INSTAPUSH_ID
          valueFrom:
            secretKeyRef:
              key: INSTAPUSH_ID
              name: authorization
        - name: INSTAPUSH_SECRET
          valueFrom:
            secretKeyRef:
              key: INSTAPUSH_SECRET
              name: authorization
        - name: FASTLY_APIKEY
          valueFrom:
            secretKeyRef:
              key: FASTLY_APIKEY
              name: authorization
        - name: FASTLY_SERVICEID
          valueFrom:
            secretKeyRef:
              key: FASTLY_SERVICEID
              name: authorization
        image: vizzuality/authorization
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 5
        name: authorization
        ports:
        - containerPort: 9000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 512M
          requests:
            cpu: 350m
            memory: 256M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
