apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: authorization
  namespace: gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: authorization
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
