apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: authorization
  namespace: core
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: authorization
  minReplicas: 10
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
