apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: authorization
  namespace: core
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: authorization
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
