apiVersion: v1
kind: Service
metadata:
  namespace: core
  labels:
    name: authorization
  name: authorization
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9000
  selector:
    name: authorization
